-- Temporarily disable RLS on all tables to test signup
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_points DISABLE ROW LEVEL SECURITY;
ALTER TABLE badges DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_badges DISABLE ROW LEVEL SECURITY;
ALTER TABLE challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE challenge_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE badge_conditions DISABLE ROW LEVEL SECURITY;